### /boss/user/detail/login
POST http://101.132.100.145:8182/boss/user/login/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjoyMDAwMCwidXNlcl9uYW1lIjoieWFvMSIsInVzZXJObyI6bnVsbCwidXNlck5hbWUiOiJ5YW8xIiwibWVzc2FnZSI6IueZu-W9leaIkOWKnyIsInVzZXJJZCI6ImIwOGY4MWM0YTI0MjExZWFiYjFmMDAxNjNlMDRhNzZjIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BTk9OWU1PVVMiXSwiY2xpZW50X2lkIjoic3lzX3d5Z2wiLCJyZWFsTmFtZSI6InlhbzEiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNjExMzUxMzcxLCJzb2Z0Q29kZSI6InN5c193eWdsIiwianRpIjoieTAwWG5rSnlrNTFoS25aaEJuZG5QbEtLVjl3PSIsImNoYW5uZWxJZCI6MSwic2hvcFVzZXJOYW1lIjoiIn0.879NFl8pztBAVX1Estailj5HlxI1UtIKgXD2ubnvj5U

{"userId":"b08f81c4a24211eabb1f00163e04a76c","redirectUri":"http%3A%2F%2Flocalhost%3A8080%2F"}